name: Continuos Integration for Laravel phpunit
on: [push]
jobs:
  PHPunit:
    runs-on: ubuntu-latest
    steps:
      - uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: '8.0'
          my-cnf: |
            innodb_log_file_size=256MB
            innodb_buffer_pool_size=512MB
            max_allowed_packet=16MB
            max_connections=50
            local_infile=1
            root-password=admin
            password=admin
