name: Continuos Integration for Laravel phpunit
on: [push]
jobs:
  PHPunit:
    runs-on: ubuntu-latest
    env:
      DB_DATABASE: test_db
      DB_USER: admin
      DB_PASSWORD: admin
    steps:
      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install dependencies
        run: composer install
      - name: Generate key
        run: php artisan key:generate
      - name: Run migrate
        run: php artisan migrate -v
      - name: Run PHPunit
        run: vendor/bin/phpunit
