name: Laravel
on: [push]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    env:
      DB_DATABASE: test_db
      DB_USER: root
      DB_HOST: 127.0.0.1
      DB_CONNECTION: mysql
    services:
      mysql:
        image: mysql:5.7
        env:
        DB_PASSWORD: admin
        MYSQL_DATABASE: test_db
        ports:
        - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      steps:
        - name: Checkout
        uses: actions/checkout@v1
        - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
        php-version: '7.4'
        - name: PHP version
        run: php -v
        - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
        - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --prefer-dist
        - name: Generate key
        run: php artisan key:generate
        - name: Verify MySQL connection
        run: mysql --version
        sudo apt-get install -y mysql-client mysql --host=127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -uroot -e "SHOW DATABASES"
        - name: Run Migration
        run: php artisan migrate -v
        env:
          DB_PORT: ${{ job.services.mysql.ports['3306'] }}
          - name: Execute tests (Unit and Feature tests) via PHPUnit
          env:
          DB_PORT: ${{ job.services.mysql.ports['3306'] }}
          run: vendor/bin/phpunit
