name: Continuos Integration for Laravel phpunit
on: [push]
jobs:

  phpunit:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: test_db
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Prepare The Environment
        run: cp .env.testing .env

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install Composer Dependencies
        run: |
          composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader
          chmod -R 777 storage bootstrap/cache
          npm install
          npm run production
      - name: Generate Application Key
        #php artisan passport:keys
        run: |
          php artisan key:generate
      # - name: Upgrade Chrome Driver
      #   run: php artisan dusk:chrome-driver

      # - name: Start Chrome Driver
      #   run: ./vendor/laravel/dusk/bin/chromedriver-linux > /dev/null 2>&1 &

      # - name: Run Laravel Server
      #   run: php artisan serve > /dev/null 2>&1 &

      - name: Run Dusk Tests
        env:
          APP_ENV: local
          APP_URL: "http://127.0.0.1:8000"
          DB_CONNECTION: mysql
          DB_DATABASE: test_db
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
          DB_USERNAME: admin
          DB_PASSWORD: admin
        run:
          php artisan migrate
          php artisan test
