name: PHP-QA
on: [push]

jobs:
  # mysql-service Label used to access the service container
  mysql:
    # Docker Hub image (also with version)
    image: mysql:5.7
    env:
      ## Accessing to Github secrets, where you can store your configuration
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: test_db
    ## map the "external" 3306 port with the "internal" 3306
    ports:
      - 3306:3306
    # Set health checks to wait until mysql database has started (it takes some seconds to start)
    options: >-
      --health-cmd="mysqladmin ping"
      --health-interval=10s
      --health-timeout=5s
      --health-retries=3

  PHPunit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install dependencies
        run: composer install
      - name: Generate key
        run: php artisan key:generate

      - name: Configure .env
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: test_db
          DB_USERNAME: admin
          DB_PASSWORD: admin

      - name: Run migrates
        run: |
          php artisan migrate

      - name: Run PHPunit
        run: vendor/bin/phpunit

  PHPlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: composer install
      - name: Run PHPlint
        run: vendor/bin/phplint --no-cache app/

  PHPcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: composer install
      - name: Run PHP CodeStyle (phpcs)
        run: vendor/bin/phpcs --standard=PSR1,PSR12 app/
